services:
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile
    ports:
      - "8081:80"  
    depends_on:
      - websocket_server

  websocket_server:
    restart: always
    container_name: websocket_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env